### ISSUE TITLE
missing unicode double vertical line

### ISSUE THREAD

**Issue by JeffFessler** [sisl/pygments-julia#2]
the current source code supports this: `∥`
Unicode Character 'PARALLEL TO' (U+2225)
https://www.fileformat.info/info/unicode/char/2225/index.htm

but not this: `‖`
Unicode Character 'DOUBLE VERTICAL LINE' (U+2016)
https://www.fileformat.info/info/unicode/char/2016/index.htm

I need the missing one because it is what you get with `\Vert<tab>` in julia REPL

I'll try to make a PR.

**Comment by JeffFessler** [comment]
In case it helps others, I just found a workaround for now in my latex source:
`\DeclareUnicodeCharacter{8214}{$\|$}`

**Comment by mykelk** [comment]
Thanks for the PR!
