### ISSUE TITLE
pygments 2.7.0 removed unirange

### ISSUE THREAD

**Issue by mossr** [sisl/pygments-julia#6]
As of 3 days ago, pygments 2.7.0 removed the `unirange` function from `pygments.utils`, thus causing "cannot import name 'unirange'" errors. 

Also, all "u" string prefixes were removed as all Python builds from 3.3+ are wide unicode compatible. https://github.com/pygments/pygments/pull/1536

I'm working on a PR for a fix now.

**Comment by mykelk** [comment]
Whoa. Thanks Robert!
